version: '3'
services:
  log_watcher:
    image: hara:token-bridge
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - WATCHER_NETWORK_URL=${WATCHER_NETWORK_URL}
      - WATCHER_NETWORK_ID=${WATCHER_NETWORK_ID}
      - WATCHER_NETWORK_ACCOUNT=${WATCHER_NETWORK_ACCOUNT}
      - WATCHER_CONTRACT_ADDRESS=${WATCHER_CONTRACT_ADDRESS}
      - WATCHER_MINT_PK=${WATCHER_MINT_PK}
      - WATCHER_MINT_PK_PATH=${WATCHER_MINT_PK_PATH}
      - DEFAULT_MINT_NETWORK_URL=${DEFAULT_MINT_NETWORK_URL}
      - DEFAULT_MINT_NETWORK_ID=${DEFAULT_MINT_NETWORK_ID}
      - DEFAULT_MINT_CONTRACT_ADDRESS=${DEFAULT_MINT_CONTRACT_ADDRESS}
      - MULTIPLE_MINT_NETWORK_ID=${MULTIPLE_MINT_NETWORK_ID}
      - MULTIPLE_MINT_NETWORK_URL=${MULTIPLE_MINT_NETWORK_URL}
      - MULTIPLE_MINT_CONTRACT_ADDRESS=${MULTIPLE_MINT_CONTRACT_ADDRESS}
      - IS_DEV=${IS_DEV}
      - SHARD_LIMIT=${SHARD_LIMIT}
      - TB_WATCHER=${TB_WATCHER}
      - TB_WATCHER_BLOCKS=${TB_WATCHER_BLOCKS}
      - STAGE=${STAGE}
      - DEBUG=${DEBUG}
      - REGION=${REGION}
      - ROLE=${ROLE}
    command: bash -c "sls deploy --stage $STAGE"